# .github/workflows/crime_data_pipeline.yml
name: Crime Data Pipeline

on:
  schedule:
    - cron: '0 */12 * * *'  # Run scraping every 12 hours
    - cron: '0 */6 * * *'   # Run analysis every 6 hours
  workflow_dispatch:  # Manual trigger

jobs:
  update-crime-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dotenv
          
      - name: Cache database
        uses: actions/cache@v2
        with:
          path: crime_data.db
          key: ${{ runner.os }}-crime-db-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-crime-db-
            
      - name: Check run type
        id: check-time
        run: |
          hour=$(date +%H)
          if [ $(($hour % 12)) -eq 0 ]; then
            echo "RUN_SCRAPER=true" >> $GITHUB_ENV
          fi
          if [ $(($hour % 6)) -eq 0 ]; then
            echo "RUN_ANALYSIS=true" >> $GITHUB_ENV
          fi
          
      - name: Run scraper
        if: env.RUN_SCRAPER == 'true'
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python main.py
        
      - name: Run analysis
        if: env.RUN_ANALYSIS == 'true'
        run: |
          python analyze_crime_data.py > reports/latest_analysis.md
          # Generate timestamp for the report
          echo "Analysis generated at: $(date)" >> reports/latest_analysis.md
          
      - name: Create reports directory
        run: mkdir -p reports
        
      - name: Update README
        run: |
          echo "# Crime Data Analysis" > README.md
          echo "Last updated: $(date)" >> README.md
          echo "" >> README.md
          echo "## Latest Analysis" >> README.md
          cat reports/latest_analysis.md >> README.md
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add crime_data.db reports/* README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update crime data and analysis [skip ci]" && git push)