# .github/workflows/crime_pipeline.yml
name: Crime Data Pipeline

on:
  schedule:
    - cron: '0 */12 * * *'
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-crime-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests python-dotenv matplotlib seaborn
    - name: Debug Database
      run: |
        echo "Checking for database..."
        if [ -f crime_data.db ]; then
          echo "Database exists"
          sqlite3 crime_data.db ".tables"
          sqlite3 crime_data.db "SELECT COUNT(*) FROM incidents;"
        else
          echo "No database found"
        fi

    - name: Run scraper
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: |
        echo "Running scraper..."
        python main.py
        echo "Scraper finished"
        if [ -f crime_data.db ]; then
          echo "Database after scraping:"
          sqlite3 crime_data.db "SELECT COUNT(*) FROM incidents;"
        fi

    - name: Create and check reports directory
      run: |
        mkdir -p reports
        echo "Contents of current directory:"
        ls -la
        echo "Contents of reports directory:"
        ls -la reports/

    - name: Run analysis and generate report
      run: |
        echo "Running analysis..."
        python analyze_crime_data.py > reports/latest_analysis.md
        echo -e "\nAnalysis generated at: $(date)" >> reports/latest_analysis.md
        echo "Report contents:"
        cat reports/latest_analysis.md

    - name: Update README
      run: |
        {
          echo "# Crime Data Analysis"
          echo "Last updated: $(date)"
          echo ""
          echo "## Latest Analysis"
          if [ -f reports/latest_analysis.md ]; then
            cat reports/latest_analysis.md
          else
            echo "No analysis available yet"
          fi
        } > README.md

    - name: Check files before commit
      run: |
        echo "Files in repository:"
        ls -la
        echo "Git status:"
        git status

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add reports/* README.md crime_data.db || true
        git status
        git commit -m "Update crime data and analysis [skip ci]" || echo "No changes to commit"
        git push || echo "No changes to push"
