# .github/workflows/crime_data_pipeline.yml
name: Crime Data Pipeline

on:
  schedule:
    - cron: '0 */12 * * *'  # Run scraping every 12 hours
    - cron: '0 */6 * * *'   # Run analysis every 6 hours
  workflow_dispatch:        # Manual trigger

permissions:
  contents: write        # Add explicit permissions

jobs:
  update-crime-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests python-dotenv

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run scraper
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: |
        echo "Starting scraper at $(date)"
        python main.py

    - name: Run analysis
      run: |
        echo "Running analysis at $(date)"
        python analyze_crime_data.py > reports/latest_analysis.md
        echo "Analysis generated at: $(date)" >> reports/latest_analysis.md

    - name: Update README
      run: |
        {
          echo "# Crime Data Analysis"
          echo "Last updated: $(date)"
          echo ""
          echo "## Latest Analysis"
          if [ -f reports/latest_analysis.md ]; then
            cat reports/latest_analysis.md
          else
            echo "No analysis available yet"
          fi
        } > README.md

    - name: Commit and push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}